In [1]:
import numpy as np
import pandas as pd
! pip install sympy
from sympy import *
from scipy.linalg import lu 

Defaulting to user installation because normal site-packages is not writeable


# a. Read a matrix A from a csv file and a vector b from another csv file 

In [9]:
#matrix=pd.read_csv('/home/kk/Documents/Matrix.csv')
A=pd.read_csv("/home/kk/Documents/A.csv")
b=pd.read_csv("/home/kk/Documents/b.csv")
#print("matrix:---------------")
#print(matrix)
print("A:---------------")
print(A)
print("b:---------------")
print(b)

A:---------------
   1  2   3
0  8  3  -2
1 -4  7   5
2  3  4 -12
b:---------------
    0
0   9
1  15
2  35


# b. Perform LU decomposition for square matrix

In [7]:
#  Do the matrix factorization.  In our case, the permutation matrix P is the identity
P, L, U = lu(A)
print('The L matrix is:')
print(L)
print()
print('The U matrix is:')
print(U)

#  Show the A = PLA
res=np.dot(P,L)
a=np.dot(res,U)
print("A:", a)


The L matrix is:
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.375       0.33823529  1.        ]]

The U matrix is:
[[  8.           3.          -2.        ]
 [  0.           8.5          4.        ]
 [  0.           0.         -12.60294118]]
A: [[  8.   3.  -2.]
 [ -4.   7.   5.]
 [  3.   4. -12.]]


#   c.Solve the equation Ax=b 

In [10]:
A=np.array(A)
b=np.array(b)
print("A:", A)
print("--------------------")
print("b:",b)
print("--------------------")

#solve the AX=b equation
x = np.linalg.solve(A, b)
print("X:",x)

A: [[  8   3  -2]
 [ -4   7   5]
 [  3   4 -12]]
--------------------
b: [[ 9]
 [15]
 [35]]
--------------------
X: [[-0.58226371]
 [ 3.22870478]
 [-1.98599767]]


#   d.Do the diagonalization of a matrix (assume it is symmetric)

In [11]:
#diagonilization of a matrix
M=Matrix(mat)
print(M)
P, D = M.diagonalize()  
print(D)

Matrix([[4, 1, -1], [2, 5, -2], [1, 1, 2]])
Matrix([[3, 0, 0], [0, 3, 0], [0, 0, 5]])


# e. Give exponential, sine and sigmoid functions on A

In [36]:
def sigmoid(x):
    return(1/(1 + np.exp(-x)))
def exponenstial(x):
    return np.exp(x)
def sinfun(x):
    return np.sign(x)

sig=[sigmoid(i) for i in A]
expo=[exponenstial(i) for i in A]
sinf=[sinfun(i) for i in A]
print("sigmoid function----------")
print(np.array(sig))
print("exponential function----------")
print(np.array(expo))
print("sign function----------")
print(np.array(sinf))

sigmoid function----------
[[9.99664650e-01 9.52574127e-01 1.19202922e-01]
 [1.79862100e-02 9.99088949e-01 9.93307149e-01]
 [9.52574127e-01 9.82013790e-01 6.14417460e-06]]
exponential function----------
[[2.98095799e+03 2.00855369e+01 1.35335283e-01]
 [1.83156389e-02 1.09663316e+03 1.48413159e+02]
 [2.00855369e+01 5.45981500e+01 6.14421235e-06]]
sign function----------
[[ 1  1 -1]
 [-1  1  1]
 [ 1  1 -1]]


# f.Find all the eigenpairs of A

In [12]:
#calculate eigenpairs
valus,vectors=np.linalg.eig(mat)
print(" Eigen Values are", valus)
print("Eigen Vactors are",vectors)

 Eigen Values are [5. 3. 3.]
Eigen Vactors are [[ 0.40824829  0.40824829  0.20788451]
 [ 0.81649658 -0.81649658  0.57986183]
 [ 0.40824829 -0.40824829  0.78774634]]
